# Generated by Django 3.0.5 on 2020-04-24 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'verbose_name': 'Yazı', 'verbose_name_plural': 'Yazılar'},
        ),
        migrations.AddField(
            model_name='blog',
            name='yayin_mi',
            field=models.BooleanField(default=True),
        ),
    ]
