# Generated by Django 3.0.5 on 2020-04-24 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_blog_yayin_mi'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='yayin_mi',
            field=models.BooleanField(default=True),
        ),
    ]
