# Generated by Django 3.0.5 on 2020-04-25 20:21

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_blog_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='icerik',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
