# Generated by Django 3.0.5 on 2020-04-26 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_yorum'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Yorum',
        ),
    ]
