# Generated by Django 3.0.5 on 2020-04-26 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_kategori'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='kategoriler',
            field=models.ManyToManyField(related_name='bloglar', to='blog.Kategori'),
        ),
    ]
