# Generated by Django 3.0.5 on 2020-04-26 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_blog_kategoriler'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kategori',
            name='ad',
            field=models.CharField(max_length=100, verbose_name='Kategori Adı'),
        ),
    ]
