# Generated by Django 3.0.5 on 2020-04-26 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20200426_2243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='kategoriler',
        ),
        migrations.DeleteModel(
            name='Kategori',
        ),
    ]
