# Generated by Django 3.0.5 on 2020-04-26 22:09

from django.db import migrations, models
import djgeojson.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20200426_2321'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mekan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=255)),
                ('lokasyon', djgeojson.fields.PointField()),
            ],
        ),
    ]
