# Generated by Django 3.0.5 on 2020-05-01 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_mekan'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='resim',
            field=models.ImageField(blank=True, null=True, upload_to='blog/'),
        ),
    ]
