# Generated by Django 3.0.5 on 2020-05-01 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_remove_blog_resim'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='resim',
            field=models.ImageField(blank=True, default='defaults/default.png', null=True, upload_to='blog/'),
        ),
    ]
