# Generated by Django 3.0.5 on 2020-05-01 23:20

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_blog_resim'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='icerik',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
